bin/magento setup:install \
--base-url=http://localhost/magento_task \
--db-host=localhost \
--db-name=mydatabase \
--db-user=myuser \
--db-password=test123 \
--admin-firstname=admin \
--admin-lastname=admin \
--admin-email=admin@admin.com \
--admin-user=admin \
--admin-password=admin123 \
--language=en_US \
--currency=USD \
--timezone=America/Chicago \
--use-rewrites=1
